webmagazin/catalog/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import catalog_page
from . import views

urlpatterns = [
    path("",catalog_page, name="catalog_page"),
    #path("catalog/",views.product_list, name='product_list'),
    re_path(r'^$', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

webmagazin/home/urls.py
from django.urls import path
from .views import home_page

urlpatterns = [
    path("",home_page, name="home_page"),
]

webmagazin/webmagazin/urls.py
#from webmagazin.catalog.views import product_list
#from webmagazin import catalog
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import include, url
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
from catalog import views

urlpatterns = [
    path('home/',include("home.urls")),
    re_path(r'^admin/', admin.site.urls),
    path('catalog/',views.product_list, name='catalog_page'),
    re_path(r'^catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),  
    path("", lambda request: redirect("/home/")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webmagazin/catalog/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_list_by_category',
                        args=[self.slug])

class Tovary(models.Model):
    name = models.TextField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    colsklad = models.IntegerField(null=True)
    sale = models.IntegerField(blank=True) 
    slug = models.SlugField(max_length=200, db_index=True, unique=True, default=None)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_detail',
                        args=[self.id, self.slug])    

    

webmagazin/home/models.py
from django.db import models

# Create your models here.

webmagazin/catalog/views.py
from typing import Any
from django.shortcuts import render, get_object_or_404
from .models import Category, Tovary

def catalog_page(request):
    return render(request, "catalog.html")

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Tovary.objects.filter(colsklad=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  './catalog.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Tovary,
                                id=id,
                                slug=slug,
                                colsklad=True)
    return render(request,
                  './catalog.html',
                  {'product': product})

webmagazin/home/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):
    return render(request, "home.html",{})

webmagazin/catalog/templates/catalog.html
{% extends 'base.html' %}
{% block catalog %}
{% include "catalog/tovary.html" %}
{% endblock catalog %}

webmagazin/catalog/templates/catalog/tovary.html
{% load static %}



	<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian">
                            {% for c in categories %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></h4>
								</div>
							</div>
							{% endfor %}
					
					</div>
				</div>
			</div>
				
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->                        
						<h2 class="title text-center">{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h2>
						{% for p in products %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">								
								<div class="single-products">								        
										<div class="productinfo text-center">
											 <img src="{% if p.image %}{{ p.image.url }}{% endif %}">
											<h2>{{p.price}}$</h2>
											<p>{{p.name}}</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>{{p.price}}$</h2>
												<p>{{p.name}}</p>
												<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
											</div>
										</div> 										
								</div>								
							</div>							
						</div>
						{% endfor %}
						{% comment %} <div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/home/product2.jpg" alt="" />
										<h2>$56</h2>
										<p>Easy Polo Black Edition</p>
										<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/home/product3.jpg" alt="" />
										<h2>$56</h2>
										<p>Easy Polo Black Edition</p>
										<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/home/product4.jpg" alt="" />
										<h2>$56</h2>
										<p>Easy Polo Black Edition</p>
										<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
									<img src="images/home/new.png" class="new" alt="" />
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/home/product5.jpg" alt="" />
										<h2>$56</h2>
										<p>Easy Polo Black Edition</p>
										<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
									<img src="images/home/sale.png" class="new" alt="" />
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										<img src="images/home/product6.jpg" alt="" />
										<h2>$56</h2>
										<p>Easy Polo Black Edition</p>
										<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
									</div>
									<div class="product-overlay">
										<div class="overlay-content">
											<h2>$56</h2>
											<p>Easy Polo Black Edition</p>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
									</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div> {% endcomment %}
							</div>
						</div>
						
					
					
				</div> 
			</div>
		</div>
	</section>

webmagazin/home/templates/home.html
{% extends "base.html" %}
{% block home %}
{% include "home/slider.html" %}
{% endblock home%}

webmagazin/home/templates/home/slider.html
{% load static %}
<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							<div class="item active">
		
								<div class="col-sm-6">
									<img src="{% static 'images/home/rasprodaga.png' %}" class="reclama"  alt="" />
								
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<img src="{% static 'images/home/zelenaya_pyatnica.png' %}" class="reclama"  alt="" />

								</div>
							</div>
							
							<div class="item">
								<div class="col-sm-6">
									<img src="{% static 'images/home/konkurs.png' %}" class="reclama" alt="" />
									
								</div>
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section>

	

webmagazin/webmagazin/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> 
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/ma.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/Footer-with-button-logo.css' %}" rel="stylesheet ">
    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/component.css' %}" />
    <script src="{% static 'js/modernizr.custom.js' %}">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">  
</head>
<body>
    {% include 'base/header.html' %}
    {% block home %}{% endblock home%}
    {% block catalog %}{% endblock catalog %}
    {% include 'base/footer.html' %}


    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

webmagazin/webmagazin/templates/base/footer.html
{% load static%}
<div class="content">
</div>
<footer id="myFooter">
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <h2 class="logo">
                    <a href="#"> <img src="{% static 'images/home/logotip.png' %}" width="100px" class="my_shop"> </a>
                </h2>
            </div>
            <div class="col-sm-2">
                <h5>Get started</h5>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Catalog</a></li>
                    <li>
                        <a href="#">Registration</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>About us</h5>
                <ul>
                    <li><a href="#">Company Information</a></li>
                    <li><a href="#">Contact us</a></li>
                    <li><a href="#">Reviews</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Support</h5>
                <ul>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Help desk</a></li>
                    <li><a href="#">Forums</a></li>
                </ul>
            </div>
            <button type="button" class="btn">Contact us</button>
        </div>
    </div>
    </div>
    <div class="footer-copyright">
        <p>© 2021 Copyright Text </p>
    </div>
</footer>

webmagazin/webmagazin/templates/base/header.html
{% load static %}
<div class="header-middle">
        <div class="container">
            <div class="row">
                <div class="col-md-4 clearfix">
                    <div class="logo pull-left">
                        <a href="{% url 'home_page' %}"><img src="{% static 'images/home/logotip.png' %}" alt="" /></a>
                    </div>
                </div>
                <div class="col-md-8 clearfix">
                    <nav>
                        <ul class ="head-menu">
                            <li><a href="{% url 'home_page' %}"> Home </a></li>
                            <li><a href=" {% url 'catalog:catalog_page' %} "> Catalog </a></li>
                            <li><a href="checkout.html"> Registration </a></li>
                            <li><a href="cart.html"> Cart </a></li>
                            <li><a href="login.html"> Login </a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>